title: Jiachen Qian
logo: /assets/img/self.jpg
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

markdown: GFM
navigation:
  - title: "Home"
    url: /
  - title: "Publications"
    url: /publications/
#description: text below image
#show_downloads: true
