title: Jiachen Qian
description: Control • Online Prediction • Distributed Filtering • Optimization
url: https://CHAINLMAN.github.io
baseurl: ""  # empty for user site

remote_theme: just-the-docs/just-the-docs

# Optional extras
color_scheme: dark          # or "dark", "light"
search_enabled: true       # built-in search
logo: /assets/img/self.jpg  # e.g., /assets/logo.png  (optional)

# Use pretty permalinks like /publications/
permalink: pretty

#description: text below image
#show_downloads: true
